name: Node.js CI

on:
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: "package.json"
      - run: npm install
      - run: npm run test
        env:
          API_KEY: ${{ secrets.API_KEY }}
          API_URL: "https://test.dochorizon.klippa.com"